#!/bin/bash

echo "🔗 Connecting RealtyDirect to GitHub"
echo "===================================="
echo ""
echo "Step 1: Create a GitHub Repository"
echo "----------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: realtydirect (or your preferred name)"
echo "3. Description: Self-service real estate marketplace with RECO education"
echo "4. Make it Public or Private (your choice)"
echo "5. DO NOT initialize with README, .gitignore, or license"
echo "6. Click 'Create repository'"
echo ""
echo "Step 2: Copy the repository URL"
echo "-------------------------------"
echo "After creating, copy the repository URL (e.g., https://github.com/yourusername/realtydirect.git)"
echo ""
echo "Step 3: Run this command with your repository URL:"
echo "-------------------------------------------------"
echo "git remote add origin YOUR_REPOSITORY_URL"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Example:"
echo "git remote add origin https://github.com/chinmay/realtydirect.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "🎉 After this, your code will be on GitHub and ready for deployment!"
